exp_name: test
gpu_id: 1
save_folder: /data2/chengyi/Multi_Raters/result/save_model/TEST/
save_log: /data2/chengyi/Multi_Raters/result/save_log/TEST/
data_name: pretrain
fold: -1

start_iter: 0
max_iter: 20000
warmup_steps: 1000
num_classes: 8

lr: 0.01
lr_adjust: fix
stepvalues: [1000, 2000, 3000]
weights: [1, 1]

weight_decay: 0.0005
gamma: 0.1
momentum: 0.9
batch_size: 16
optim: SGD
save_freq: 400
display_freq: 20
val_freq: -1
num_workers: 4

model_name: Resnet
transfer: False

pretrain_weights: None
best_mode_for_vis: None